services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: metr_site
      POSTGRES_PASSWORD: metr_site
      POSTGRES_DB: metr_site
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U metr_site"]
      interval: 10s
      timeout: 5s
      retries: 3

  metr-site:
    build:
      context: ./metrouchet_site
    container_name: metr_site
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media

  nginx:
    image: nginx:latest
    container_name: metr_site_nginx
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/static
      - media_volume:/media
    ports:
      - "80:80"
    depends_on:
      - metr-site

volumes:
  static_volume:
  media_volume: